backend:
  name: github
  repo: cityofaustin/grackl
  branch: master

publish_mode: editorial_workflow

media_folder: "src/images" # where media files will be stored in the repo

collections:
  - name: "project"
    label: "Project"
    folder: "src/pages/project"
    create: "true"
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary Description", name: "summary", widget: "markdown"}
      - {label: "Stage", name: "stage", widget: "select"}
      - {label: "Budget", name: "budget", widget: "number"}
      - {label: "Funding Source", name: "funding_source", widget: "string"}
      - {label: "Lead Department", name: "department", widget: "string"}
      - {label: "Partner Organizations", name: "partners", widget: "string"}
      - {label: "Contact Person", name: "contact_name", widget: "string"}
      - {label: "Contact Email", name: "contact_email", widget: "string"}
      - {label: "Related City Goals", name: "goals", widget: "string"}
